### ISSUE TITLE
How to install ???

### ISSUE THREAD

**Issue by mtsmayad** [mikesprague/bigred-link#1]
Hi,

I am no knowledge of programin and want to run url shortener on my webhost, please give a tutorial how to make work ?!

Regards,

**Comment by mikesprague** [comment]
Installation will vary based on hosting provider, it would be more appropriate to ask their support how to install/host a Node.js application.

I have, however, added some basic instructions for running the project to the [README.md](https://github.com/mikesprague/bigred-link#bigredlink) file. Hope that helps!
